### ISSUE TITLE
configFile location

### ISSUE THREAD

**Issue by eternal-flame-AD** [YKilin/pxder#4]
https://github.com/YKilin/pxder/blob/aca40d5200d95038dfb91e2eedee5e7896393c39/src/index.js#L19

这一行逻辑有点奇怪，可以存在appdata/~的

这样子在linux下会权限不足
```
fs.js:113
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/lib/pxder.config.json'
    at Object.openSync (fs.js:434:3)
    at Object.writeFileSync (fs.js:1154:35)
    at Function.initConfig (/usr/lib/node_modules/pxder/src/index.js:37:7)
    at Function.readConfig (/usr/lib/node_modules/pxder/src/index.js:54:13)
    at Object.<anonymous> (/usr/lib/node_modules/pxder/bin/pxder:37:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

**Comment by YKilin** [comment]
emmm，当时是想将配置文件放在脱离项目本身的位置以免更新导致配置被删除，但又没有什么好的想法

请问`appdata/~`指的是什么，顺便关于这个问题有没有通用的解决方法……

**Comment by eternal-flame-AD** [comment]
操作系统有规定应用程序把配置存在哪里的～
可以参考下[这个](https://stackoverflow.com/questions/19275776/node-js-how-to-get-the-os-platforms-user-data-folder)
或者试试[这个](https://www.npmjs.com/package/appdata)现成的包

**Comment by YKilin** [comment]
好的，谢谢大佬指导，有时间我去改正
